spring:
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://localhost:3306/shoppingify
    username: root
    password: 1 guy 2 code
  jpa:
    hibernate.ddl-auto: update
    generate-ddl: true
    show-sql: true

